"""add morning_order to podcasts

Revision ID: 002_add_morning_order
Revises: 001_initial
Create Date: 2025-12-06 19:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_morning_order'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('morning_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_podcasts_morning_order'), 'podcasts', ['morning_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcasts_morning_order'), table_name='podcasts')
    op.drop_column('podcasts', 'morning_order')
    # ### end Alembic commands ###
